### ISSUE TITLE
CPLEX Error  1217: No solution exists.

### ISSUE THREAD

**Issue by maringos** [euba/BacArena#101]
I am trying Cplex and I am experiencing this problem:
```
> sybil::SYBIL_SETTINGS("SOLVER","cplexAPI")
Loading required package: cplexAPI
> 
> library(BacArena)
Loading required package: sybil
Loading required package: Matrix
Loading required package: lattice
Loading required package: ReacTran
Loading required package: rootSolve
Loading required package: deSolve
Loading required package: shape
BacArena paper: https://doi.org/10.1371/journal.pcbi.1005544
 Tutorial: https://CRAN.R-project.org/package=BacArena/vignettes/BacArena-Introduction.pdf
 Development and help: https://github.com/euba/bacarena
> arena <- Arena()
> data(Ec_core)
>   x<-Ec_core
>   bac_wild <- BacArena::Bac(model=x) 
>   arena <- BacArena::Arena(n=10, m=10)
>   arena <- BacArena::addOrg(arena, bac_wild, amount=10)
>   arena <- BacArena::addSubs(object = arena,smax = 1)
>   sim <- BacArena::simEnv(arena, time=3)

iteration: 1     organisms: 10   biomass: 5.044588 pg 
                 count  biomass %
ecoli_core_model    10 5.044588 0

CPLEX Error  1217: No solution exists.

Error in cplexAPI::getPiCPLEX(lpob@problem@oobj@env, lpob@problem@oobj@lp,  : 
  object of type 'S4' is not subsettable
> 

```

**Comment by maringos** [comment]
I would suggest to deactivate this loop, because shadow costs are not supported. 
https://github.com/euba/BacArena/blob/d86c98b62413c2339cce0f4c957a8e5c825c8b4f/R/Organism.R#L382-L386

**Comment by jotech** [comment]
Unfortunately, the issue is not straight forward. Shadow costs are supported by cplex but to get it work I had to change how sybil's optimizeProb is called:
https://github.com/euba/BacArena/blob/204ced1ea5cf2e166bc47f3f47219377c75c1eec/R/Organism.R#L296-L297
This should not do any harm but actually it does and that is why changes were reversed again fbd6b63343668bd2c78578a760b8c500e3ae292b
From my gut feeling, I would say it is related to the linear program object and the access to it.
I think we should integrate a ``shadow`` parameter for ``simEnv()`` to enable and disable shadow costs. I will come up with a commit.

**Comment by euba** [comment]
I agree that it makes sense to create a `shadow` flag and then wrap an if statement around the retrieval of the shadow costs. This is useful in any case, because then the shadow costs are not stored in case you don't want them.
But it is still strange that cplex doesn't want to execute this. It looks like it is not recognizing the object given to it. Maybe it is somehow connected with the solution status, even though the if statement asks for the solution to be ok?

**Comment by jotech** [comment]
It is really strange @euba because it is working when I change the ``optimizeProb()`` call as mentioned above! But this has side effects with the fba solution object ... no clue from my side ..

**Comment by maringos** [comment]
Hi,

the 1217 error returns at the final steps of the following arena settings:
```
sybil::SYBIL_SETTINGS("SOLVER","cplexAPI")
library(BacArena)
arena <- Arena()
data(Ec_core)
x<-Ec_core
bac_wild <- BacArena::Bac(model=x) 
arena <- BacArena::addOrg(arena, bac_wild, amount=10)
arena <- BacArena::addSubs(object = arena,smax = 1)
sim <- BacArena::simEnv(arena, time=10, sec_obj = 'mtf')
```

**Comment by maringos** [comment]
The problem has disappeared following the growth-related fixes....
e.g. https://github.com/euba/BacArena/commit/474e0a5775afa9c578c623ba91b3f4ca2c42e094
https://github.com/euba/BacArena/commit/0cbb7ee008396c59693f884a9a2a91a3971b3596

What a nice growth curve....
![rplot01](https://user-images.githubusercontent.com/17548206/39780582-05b543b2-530d-11e8-9fa1-8b2ba7a24e68.jpeg)
