### ISSUE TITLE
Growth-related question

### ISSUE THREAD

**Issue by maringos** [euba/BacArena#109]
Hi! Could you explain to me what is the role of 1.5 in this line? https://github.com/euba/BacArena/blob/474e0a5775afa9c578c623ba91b3f4ca2c42e094/R/Organism.R#L282

**Comment by euba** [comment]
Hi,

This line is to set the upper bound of the growth per cell (so that the cell doesn't simulate unrealistic growth values). The 1.5 value is just a factor to allow some room for the biomass to accumulate (if the value is set to 1 the growth curves don't look so smooth and are stepwise). We tried out different values for this factor (from 1 to 2) and found 1.5 to best suited.

**Comment by maringos** [comment]
Many thanks for the answer. Just an idea: please comment accordingly the line so that future users know why 1.5 is there.
