### ISSUE TITLE
Support for AGORA models

### ISSUE THREAD

**Issue by microsud** [euba/BacArena#116]
Hi BacArena team,
Nice tool! Was searching for R based tools for such type of analysis. I was wondering if there is a possibility to include AGORA models as datasets similar to `Ecoli_core` or have a utility function to directly read .xml or .mat file into R as modelOrg objects. 
If these are not possible, could you please direct me to resources where I can try to read .xml file into R as modelOrg?
I new to this type of data structures and metabolic models. 
```
library(rsbml) 
library(BacArena)

mod1 <- rsbml_read("./models/Acaccae.xml", dom = F)
mod1

bac <- Bac(mod1)
Error in sybil::findExchReact(model) : 
  needs an object of class modelorg, Matrix or matrix!

arena <- Arena(n=20, m=20)
arena <- addOrg(arena,mod1,amount=20)
arena <- addDefaultMed(arena, bac)
arena <- addSubs(arena, smax=0.5, mediac="EX_glc(e)", unit="mM")

arena
```
attached is the zipped xml file.

The sybilSBML package is no longer available at [CRAN ](https://cran.r-project.org/web/packages/sybilSBML/index.html)
It would be a great help if there is a seamlessly integration of output from other resources directly into the workflow of BacArena without intermediate dependencies. 
Many thanks in advance!

[Acaccae.zip](https://github.com/euba/BacArena/files/2159160/Acaccae.zip)

Cheers,
Sudarshan

**Comment by jotech** [comment]
Hi Sudarshan,
you are completely right this is a problem right now because `sybilSBML` has issues with CRAN policies because they do not want to install the latest libsbml version on their testing servers. That is why it is not available right now. The maintainer is currently trying to solve it. Maybe it will help if you write a mail to CRAN so that they get feedback that the package is needed?
Meanwhile you can try this workaround:
- Download the current package from the [sybil homepage](https://www.cs.hhu.de/fileadmin/redaktion/Oeffentliche_Medien/Fakultaeten/Mathematisch-Naturwissenschaftliche_Fakultaet/Informatik/Bioinformatik/sybilSBML_3.0.2.tar.gz)
- install it manually: `R CMD INSTALL sybilSBML_3.0.2.tar.gz`

Let me know if this helps you out,
best johannes
