### ISSUE TITLE
cellweight_sd and different optimization result

### ISSUE THREAD

**Issue by maringos** [euba/BacArena#118]
Hi,

Could you be so kind to explain to me what is going in the following lines?

https://github.com/euba/BacArena/blob/1f62c0a1415f2663628cdd03fc601a1cca667be5/R/Organism.R#L268-L270

I am asking because I have realized that if` cellweight_sd=0 & diffusion=F`, then the result is the same as a sybil optimization. Morever if sd is not zero, there is fluctuation in the lower bounds and so fluctuation in the optimization solution. This leads to the phenomenon that I have no clue which replication to trust....So I would like to learn what is behind the code in these lines.

Regards,
George

**Comment by maringos** [comment]
By the way since lower bounds are usually negative, why `lb<=lobnd[reacts]` is < and not >

**Comment by jotech** [comment]
Hi,
the idea behind line ``268`` is that lower bounds for organism, which already grew a lot, should be also higher (i.e. bigger cells -> more surface -> more transporter -> higher uptake).
In case of the other line ``270``, there is the issue of two conceptually different lower bounds. One is defined by the environment and the other by the organism/model. It could be the case that there is plenty of glucose available but the actual uptake of glucose is limited by the model itself. This is why there is a test ``lb<=lobnd[reacts]``. If the lower bound given by the environment (``lb``) is smaller (i.e. more negative => in absolute term bigger!) than the model lower bounds (``lobnd``), then the model lower bounds are used because they are more restrictive. I see that it can be irritating because of the negative nature of lower bounds. Maybe an example can help: The model lower bound of glucose uptake may be limited by EX_glc=-5 and the available glucose on a grid cell may supposed to be 10. Then ``-10 <= -5`` holds true and -5 is taken as lower bound because the model uptake capacity is more limiting than the environmental constrain. 
Let me know if this makes sense for you.

**Comment by maringos** [comment]
Many thanks for your answer. I understand the concept and I will go directly to the example of yours.
CASE1
lf the model has  lower bound -5, then lb=-5
If the environment has a value of -10, then lobnd[reacts]=-10
Then the line 270 dictates that the lb should be remained -5, **which is OK; -5 is the maximum allowed.**
CASE2
If the model has  lower  bound -10 then lb=-10
If the environment has a value of -5, then lobnd[reacts]=-5
Then the line 270 dictates that the lb should be -10, **which is strange, because the model takes more flux than existed in the environment**. What is your opinion on that?

Except for this question, I would like to ask you about the influence of cellweight_sd on the fluxes. Unless you do many replications, it is difficult to trust the result, because the dryweight will fluctuate (+/-) in the sd range. Is this idea correct?

Many thanks for your helpful answer above
/GM

**Comment by maringos** [comment]
For the CASE2 I am wrong....
The lb should be -5 at the end! Do we agree?
/GM

**Comment by jotech** [comment]
I think you are mixing the variables. If you are referring to the code above, then ``lb`` is given by the environment:
https://github.com/euba/BacArena/blob/1f62c0a1415f2663628cdd03fc601a1cca667be5/R/Organism.R#L246
And as you said in your second post the final lower bound will be -5 in this case what makes completely sense and is the expected behavior, as far as I can see.

Concerning your second question, I cannot see something related to ``cellweight_sd``?!
If you are talking about ``cellweight_mean``, then this is not random but a fixed number set in the Bac constructor (default 0.489). So this should not be a source of variance...

**Comment by maringos** [comment]
Hi! I was confused; You are right. Concerning the `cellweight_sd`, my idea is that the starting `dryweight` (not the `cellweight_mean`) of the model is random and is influenced  by  `cellweight_sd`. As a result, the lower bounds are different at the end...
