### ISSUE TITLE
Designing a medium

### ISSUE THREAD

**Issue by utkinaira** [euba/BacArena#137]
Hi everybody!

I would like to design a model of a community under different diets and I am wondering if it is possible to add substances to arena like a proportion (e.g., amino acids:sugars  = 6:4) or somehow other way similarly?
And if it's not possible, would it make sense to do it this way:

```
arena <- addSubs(arena, 100) 
arena <- changeSub(arena,60,c("aminoacid-1", "aminoacid-1", ... , "aminoacid-N"))
arena <- changeSub(arena,40,c("sugar-1", "sugar-2", ... , "sugar-N"))
```

Thanks a lot in advance, appreciate any help! :)

**Comment by euba** [comment]
Hi,

if you add the first line with `arena <- addSubs(arena, 100)` you will add all metabolites with an ammount of 100 mM. I would recommend to add the metabolites like this:
```
arena <- addSubs(arena,6*x,c("aminoacid-1", "aminoacid-1", ... , "aminoacid-N"))
arena <- addSubs(arena,4*x,c("sugar-1", "sugar-2", ... , "sugar-N"))
```
With `x` you can adjust the ammounts of metabolites that you want to add to the medium. I would run a sensitivity analysis of `x` to figure out what the right ammount should be: If you add too little it won't be enough for growth, but if you add too much the nutrients are not limiting and you wouldn't see a difference due to the proportion you added. This also depends on the number of individuals in the environment.

Cheers, Eugen

**Comment by utkinaira** [comment]
Thanks a lot for a quick response, I'll do that!
