### ISSUE TITLE
Set or control pH

### ISSUE THREAD

**Issue by utkinaira** [euba/BacArena#157]
Hi all,

I am wondering if that is possible to set and/or control the pH of the environment?
Thanks in advance!

Irina

**Comment by jotech** [comment]
hi @utkinaira 
this a very good point, indeed! In principle you can set the pH by adding or removing protons from the arena, for example:
```R
arena <- Arena()
arena <- addSubs(arena, smax=1000/(10^4.7), mediac="EX_h(e)", unit="mM", add=F) # pH=4.7
```
But in general I would argue against it because the representation of protons in flux balance analysis seems to be incomplete (e.g.: a lot of cellular processes that use and produce protons are missing and some models simply take up protons which are then used for the proton gradient). In addition, many environmental processes which could influence proton concentration are not captured. That is why I would recommend to add sufficient protons to the medium so that they are not limiting but also not to spend too much efforts on interpretation (predicted uptake/release of protons) just because the issue is beyond the scope of the approach. Nonetheless it is important to avoid futile cycles in individual models that can cause the production or consumption of protons out of nothing.

**Comment by utkinaira** [comment]
Hi @jotech, 

Thanks for your reply! 
Yes, I was also concerned about the lack of some processes that might use/produce protons. I guess then there is no reliable way to set a pH. 
Thanks a lot for a detailed explanation :)

Best,
Irina

**Comment by jotech** [comment]
you are welcome! thanks for using bacarena :)
