### ISSUE TITLE
Clarification needed

### ISSUE THREAD

**Issue by maringos** [euba/BacArena#32]
The situation I am going to describe is not a bug, but appears due to insufficient documentation.
I am running an experiment, with no substances. As it is logical, the biomass and the number of the organisms are decreasing. If someone checks the evalArena result (retdata = T), there is information about growth. These numbers are not negative, but getting lower and lower. What is the physical meaning of this information? What about the unit?

**Comment by euba** [comment]
Hi, the numbers you are referring to are not directly growth rates, but the accumulated growth or biomass (e.g. dry weight). The values are decreasing, because the cell is loosing biomass (starving) if it cannot metabolize substrates. This is implemented by decreasing an experimentally (decrease of biomass from stationary phase compared to death phase) determined factor (deathrate) from the current biomass. If the value of the current biomass is below another experimentally (minimal possible biomass of one cell) determined factor, the cell dies out and is removed. The unit of the biomass/dry weight is in pg. So the tables that you get from `evalArena(retdata=T)` contain the dry weight (in pg) for each cell in the environment.
Is this clear? Do you think this information should be in the tutorial?

**Comment by maringos** [comment]
Many Thanks for this hint. Actually, this information may be useful in tutorial. Also it may be useful to state this death value for each organism. Is the default value or not? it is useful to know the actual number or how to find that.

**Comment by euba** [comment]
Thanks for your suggestion. The values are calibrated according to experimental studies on E.coli (you can check out this manuscript: Loferer-Krobacher M et al. Determination of bacterial cell dry mass by transmission electron microscopy and densitometric image analysis. Applied and Environmental Microbiology). I now updated the documentation to include the default values: After updating the package with `install_github('euba/BacArena')` you can check the updated documentation with `?'Organism-class'`.

**Comment by maringos** [comment]
I just updated my BacArena and I saw your changes. The only point I would like to highlight is that  the evalArena result (retdata = T) shows jusr growth. By writing "accumulated growth or biomass (e.g. dry weight)"  to the respective documentation, you may help people in understanding the physical meaning of the growth. If you feel that this suggestion is not necessary, you may close the issue. The situation is clear.

**Comment by jotech** [comment]
I agree completely. The growth model is not easy to understand because there are many parameters and slots. We addressed this in the bacarena manuscript which should help in future.
Orgdat as accumulated growth is described in ``help("Arena-class")``.
We should think about renaming orgdat$growth to orgdat$biomass. What do you think @euba ?

**Comment by euba** [comment]
Yes, we could do this. Do you think that maybe orgdat$dry_weight is better, because orgdat$biomass sounds like the solution of a single FBA?

**Comment by jotech** [comment]
Does it really sounds so? In my opinion dry weight is more complicated. Isn't the FBA solution just a growth rate? I would say biomass is the quantity and dry weight its measured unit?

**Comment by maringos** [comment]
I would propose: "Mass", a general term. Just please explain that in detail in the [reference manual](https://cran.r-project.org/web/packages/BacArena/BacArena.pdf).

**Comment by jotech** [comment]
We still need a solution here..

Let's consider the basic definitions at wikipedia:
1. **Biomass** _is organic matter derived from living, or recently living organisms_
2. **Mass** _is a property of a physical body. It is the measure of the quantity of matter an object contains._
3. **Dry weight** _is the weight of a vehicle without any consumables, passengers, or cargo._

I'm in favor of biomass because it's the clearest definition.

**Comment by maringos** [comment]
Biomass is fine by me. A simple user always wants easy terms :)

**Comment by euba** [comment]
Yes, biomass is probably the best term.

**Comment by jotech** [comment]
Should work now, tried to find all direct and indirect references to orgdat$growth. Could you give it a try?

**Comment by maringos** [comment]
As far as I checked, you have changed the column name to biomass. I will close now the issue. Many thanks!
