### ISSUE TITLE
 sim@medlist +1 iteration

### ISSUE THREAD

**Issue by maringos** [euba/BacArena#36]
In a 5-iteration simulation, the sim@medlist goes up to 6. 

- Why does it occur?

- If the initial condition is 1, then the last is 6. 

- But why is the initial condition not 0?

I do not know how much related is this issue to the [Issue 12](https://github.com/euba/BacArena/issues/12) or the [Issue 13](https://github.com/euba/BacArena/issues/13).

**Comment by euba** [comment]
Hi, yes the first element is the initial condition. It is not stored in position 0, because the indexing in R starts with 1 and not zero. So if you create a vector in R for example you will only get the first element by indexing with 1:
``
test = 0:9 #Create a vector from 0 to 9
test[1] #get first element of vector
test[0] #does not work
``

**Comment by jotech** [comment]
But this indeed causing some irritation in the code especially when it comes to ``time+1`` parts...
And yes it is related to issue #13 which also suggest an alternative.

**Comment by maringos** [comment]
Many thanks for your answer. Any relevant discussion should be held in issue #13 then.
