### ISSUE TITLE
Human_data

### ISSUE THREAD

**Issue by maringos** [euba/BacArena#37]
In [issue #32](https://github.com/euba/BacArena/issues/32) [Euba](https://github.com/euba) 'talked' about E.Coli parameters, but also there is a Human class in BacArena. Should we add some similar info for a representative human cell series ? (I include myself even I am not an official [aut] or [cre])

**Comment by jotech** [comment]
The aut/cre labels are from CRAN which has a more stricter authorship policy. Additionally, CRAN only distributes R packages. Development is taken place at github and is open to all kinds of contributions.
Concerning your question: For sure default values for the human class are welcome. But think about what might be a representative cell out of the diverse and specialized multi-cellular tissues? What's your guess?

**Comment by maringos** [comment]
You are 100% correct, but the same is for true E.Coli and other bacteria. Please check for [HeLa cells ](http://bionumbers.hms.harvard.edu/search.aspx?log=y&task=searchbytrmorg&trm=HeLa&time=2017/01/20+07:09:46.420&rpp=100)how many data exist.

**Comment by jotech** [comment]
But for bacteria is easier to find a representative since we do not consider morphology.  Variance in human cells is much greater think about cell size from 10µm to meters.

**Comment by maringos** [comment]
I do not disagree, but what is worse? To simulate 10µm cell with E.Coli data or with a neuron data?

**Comment by jotech** [comment]
Is this the only alternative? Why not simply using
```R
hum <- Human(recon2, cellarea=5000, minweight=100, maxweight=2000, cellweight_mean=1000, cellweight_sd=500)
```

**Comment by maringos** [comment]
The same is true for Bacteria. My question is not how to add them, but  why there is no default for human cells - imagine somebody that wants to check one model briefly. Why should she or he search in literature for human cell, when she or he has ready data for microbes' default cell?  That I call different perspectives ;)

**Comment by jotech** [comment]
And I'm talking about the difference to define a default for microbes in comparison to a human cell. Did you consider my variance argument? For sure it is also a question of perspective, but since we haven't integrated different size scales yet it hasn't impact anyway.

**Comment by maringos** [comment]
So I will close this issue, but we should keep it in mind, when this integration takes place! :)

**Comment by euba** [comment]
Just to give also my opinion: I think human cells are particularly difficult, because it's hard to come up with an objective that they should optimize. For bacteria it is simpler, because there is several evidence that shows that biomass is a good approximation to model different phenotypes and metabolic behavior. That's why we calibrated all parameters according to the biomass of a cell. As for human cells, the biomass objective would be probably more likely for cancer or strongly growing cells. 
We should maybe think about relaxing the parameters for the human class and also having the option that the cell stays at a constant biomass without accumulation and just perform the given objective (e.g. ATP maintenance, transport of nutrients, ...) to update the flux vectors and concentrations.
