### ISSUE TITLE
Installation Problems and Suggestion

### ISSUE THREAD

**Issue by maringos** [euba/BacArena#42]
- When someone installs for first time BacArena, she or he faces this problem:
```
trying URL 'https://cran.rstudio.com/src/contrib/Rcpp_0.12.9.tar.gz'
Content type 'application/x-gzip' length 2372283 bytes (2.3 MB)
================================================
downloaded 2.2 MB

Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot download all files
In addition: Warning messages:
1: In download.file(url, destfile, method, mode = "wb", ...) :
  downloaded length 2309197 != reported length 2372283
2: In download.file(url, destfile, method, mode = "wb", ...) :
  URL 'https://cran.rstudio.com/src/contrib/Rcpp_0.12.9.tar.gz': status was 'Failure when receiving data from the peer'
Warning in download.packages(x$name, destdir = dest_dir, repos = x$repos,  :
  download of package ‘Rcpp’ failed
Error in download.packages(x$name, destdir = dest_dir, repos = x$repos,  : 
```
This problem can be solved if you ask individually for a Rcpp installation. Consider if this happens due to BacArena or to Rcpp itself. 

- Also please consider to hide all the processes during the installation (hundreds of useless lines for a simple user). If something is needed, that is the error(s) reports.

- Also please consider the duration of installation. I understand that a 100% new Linux OS has no package installed and the installation time is longer, but is there any other reason behind this behavior?

**Comment by euba** [comment]
I just installed BacArena in a new linux environment and I can confirm the long installation time. This is mostly because of all the dependencies that are used by BacArena and need to be installed. If no LP solver is installed before, it takes a long time to install glpk.
It's difficult to find the solution for this, because we don't have control over the installation time of the dependencies. We could remove some of them, but this would mean less features for BacArena.
As for the output during the installation, we also don't really have control over this, since this is standard in CRAN installations to show every step.
I didn't encounter the problem of installing Rcpp. Based on your error it looks like he couldn't fetch the correct package source. Maybe it is because of the installation mode (CRAN, devtools) you selected.
