### ISSUE TITLE
Arena Problems arise  #2

### ISSUE THREAD

**Issue by maringos** [euba/BacArena#50]
```
library(BacArena)
arena = Arena(n=50, m=50)
#PROJECT THESIS SIHUMI
sihumi<-readRDS("~/hetero/sihumi/sihumi2_new.RDS")
for(i in seq_along(sihumi)){
  bac <- BacArena::Bac(model=sihumi[[i]])
  arena <- BacArena::addOrg(arena, specI=bac, amount=5)
  arena = addDefaultMed(object = arena,org = bac)
 }
traceback()
sim <- simEnv(arena, time=2)  
traceback()

```
and the problematic result:
```
iteration: 1 	 organisms: 40 	 biomass: 19.20516 pg 
                                                   count  biomass %
Anaerostipes_caccae_DSM_14662                          5 2.430458 0
Bacteroides_thetaiotaomicron_VPI_5482                  5 2.090496 0
Bifidobacterium_longum_NCC2705                         5 2.805954 0
Blautia_producta_DSM_2950                              5 2.755307 0
Clostridium_ramosum_VPI_0427_DSM_1402                  5 2.420882 0
Escherichia_coli_str_K_12_substr_MG1655                5 2.043223 0
Lactobacillus_plantarum_subsp_plantarum_ATCC_14917     5 2.282607 0
Clostridium_butyricum_DSM_10702                        5 2.376229 0
Error in if (sum(subch) != 0) { : missing value where TRUE/FALSE needed
> traceback()
4: addEval(evaluation, arena)
3: addEval(evaluation, arena)
2: simEnv(arena, time = 2)
1: simEnv(arena, time = 2)
```

**Comment by euba** [comment]
Hi, thanks for reporting. The problem was addDefaultMed. It takes the constraints of the exchange reactions from the models you load in and uses the values as concentrations. However, when the exchange reactions have infinite values as constraints (which is normal for COBRA models), it also puts infinite in the concentrations, which causes the problem (infinite values are not supported in BacArena). I changed the code in the last commit to set the value to a very high concentration instead of infinite, so it works now.
The models you load in seem to be unconstrained (everything set to infinite), maybe it makes more sense to have a diet constrained? But it depends on the application (-;

**Comment by maringos** [comment]
Thank you very much for this analysis....really helpful.
