### ISSUE TITLE
Information in help missing

### ISSUE THREAD

**Issue by maringos** [euba/BacArena#51]
Dear All,
I am trying to figure out where the information on the default diffusion factor for arena is saved. To my knowledge, the default diffusion coefficient is the glucose's one, but where is that written?
Regards,
GMaringos

**Comment by euba** [comment]
Hi, yes the default is the diffusion coefficient of glucose in aqueous solution (6.7e-6 cm^2/s). I added this to the help documentation in the Substance class.

**Comment by maringos** [comment]
Thank you. Actually how can I change that parameter? In which variable is this parameter saved?

**Comment by euba** [comment]
You can change it in the `addSubs` function by changing the "difspeed" paramerter, e.g. `addSubs(arena,smax,c('EX_ac(e)','EX_for(e)'),difspeed=6.7e-6)`. Make sure that what you set as "difspeed" is a vector with the different diffusion constants you want to set, otherwise if you just give one value as in my example, the function will set this value for all metabolites you give as an input.
