### ISSUE TITLE
Specifying bacterial doubling time

### ISSUE THREAD

**Issue by Microbiology** [euba/BacArena#90]
As I am getting started and trying to setup my own simulations, I am unsure about how to specify the doubling time of the bacteria, after reading through the documentation. Some bacteria grow very fast (like E coli which can double every few minutes) and some are slower (Mycobacteria can take hours and days to double). As far as I can tell, it is not included in the SBML model file, so I would guess that I have to specify that somewhere else. I'm just not seeing where.

How have you addressed doubling time in your experience? Where should I be looking for how address this in my own BacArena modeling?

Thanks so much for writing this awesome software! :)

**Comment by euba** [comment]
Hi,

Thank you for your kind words and interest :)

The doubling time is not directly specified by a parameter, but an emergent property of the simulation. Based on an exponential growth function (or linear if you specify "growtype" accordingly) biomass computed by FBA is accumulated in each iteration till a threshold is reached and the cell divides. The threshold is set in the parameter "maxweight", which is the maximum biomass an organism can achieve and set by default to the experimental E.coli value of [1.172 pg](http://aem.asm.org/content/64/2/688.long).

So that means that the doubling time will be automatically predicted and will be always different depending on the medium or other conditions you impose, e.g., E.coli has a simulated faster doubling time on a rich medium compared to a minimal medium.

Cheers, Eugen

**Comment by Microbiology** [comment]
I see, thanks. So it sounds like it will be important to change the max biomass value to match any other organism used.

Also just so I make sure I've got it, is each iteration a true hour (as mentioned on the plot x-axis) or is it just a single calculation iteration? I'm just thinking about whether the time associated with each iteration could vary by bacterium.

Thanks so much for your clarifications! :)

**Comment by euba** [comment]
If you can find the max biomass for a cell in the literature or experiments, it would be of course best to integrate it for the used organism. In case it is not available, I think the E.coli value is a good approximation, except if it is really an organism that has much bigger or smaller cells.

All plots should be updated to show the true (simulated) hour and not the simulation step, but the objects and list are reported with iteration steps. In case a plot shows iteration steps, please tell us and we update :)

**Comment by Microbiology** [comment]
Thanks, this is really helpful! I appreciate the insight and think I understand much better. :)
