### ISSUE TITLE
Parallelization: Alternative example approaches

### ISSUE THREAD

**Issue by maringos** [euba/BacArena#94]
Hi,

First of all, this is not a bug. 
I am writing to ask for your feedback concerning the parallelization approach for replications I use:
1. Create your setting and save it as a function:
```
#sim configuration as function
sim <-function(u){
  data(Ec_core)
  x<-Ec_core
  bac_wild <- BacArena::Bac(model=x) 
  arena <- BacArena::Arena(n=10, m=10)
  arena <- BacArena::addOrg(arena, bac_wild, amount=10)
  arena <- BacArena::addSubs(object = arena,smax = 1)
  sim <- BacArena::simEnv(arena, time=3)
}
```
2.  Run parallelization
```
library(BacArena)
library(foreach)
library(doMC)
registerDoMC(4) # available cores

a<-c(1:4) # replications
simlist <- foreach (i = seq_along(a))  %dopar% {
  sim()}
```
What is your opinion as BacArena developers?

Regards,
George

**Comment by jotech** [comment]
As far as I know doMC is working on Linux only. DoParallel works on all common systems (linux, win, macos). In the past, I encountered some problems with initialization of parallel loops. The problem was to ensure that the replicates have different seeds. Otherwise the simulation will get the same random numbers and will be the identical. That is not what you want for in silico replicates. If I remember correctly, this was the reason for using parallel's PSOCK instead of FORK even if it needs more memory. Haven't used doMC so far but as far as I can [see](https://stackoverflow.com/questions/28989855/the-difference-between-domc-and-doparallel-in-r), it also uses the parallel package and is very similar to DoParallel. But what are your experiences? Does it produce proper replicates?

**Comment by maringos** [comment]
Many thanks for your helpful answer! I have experienced one serious problem. For an unknown reason to me, the doMC cannot handle large memory tasks.

**Comment by jotech** [comment]
Is the system's memory limiting or does the doMC crash? You should have a look on the memory consumption because the R process could be killed by the system if it is in danger to consume all of the memory. But in this case it is not a direct problem of doMC. And what about the replicates? Are they different?

**Comment by maringos** [comment]
The error message was:
```
Error in sendMaster(try(lapply(X = S, FUN = FUN, ...), silent = TRUE)) : 
  long vectors not supported yet: fork.c:376
Calls: %dopar% ... <Anonymous> -> mclapply -> lapply -> FUN -> sendMaster
Warning message:
In mclapply(argsList, FUN, mc.preschedule = preschedule, mc.set.seed = set.seed,  :
  scheduled core 1 encountered error in user code, all values of the job will be affected

```
According to [this site](https://stackoverflow.com/questions/23231183/mclapply-long-vectors-not-supported-yet), it is connected to memory. The code was running in a HPC cluster. I have not searched for differences between the replicates (only few failed) because of the message "all values of the job will be affected" .

**Comment by jotech** [comment]
I also found doMPI recommended on linux clusters. And what about the replicates are the using different seeds?

**Comment by maringos** [comment]
I will check out the doMPI. Well, I cannot say anything about the seeds ~ I am amateur to understand every detail of the topic, but I did something like that:
```
arithmetic <- 20
doMC::registerDoMC(arithmetic)
replicalist <- foreach::foreach(R = seq_along(44:50))  %dopar% 
  {  
    df[1,1] = R
    z = df[1,1]
    replica <- lapply(1:replicator, function(x){sim(z)})
  }

```

**Comment by jotech** [comment]
You can check if the replicates are different by comparing e.g. the initial position of bacteria, movement, substance concentration (every parameter which uses random numbers to make the arena unique i.e. a different setup for simulation). To be sure about it is quite crucial because otherwise you just doing the same _identical_ simulation again and again. So your replicates are no replicates!

**Comment by maringos** [comment]
Dear All,
I think that the following configuration is a working example how to use many cores to conduct simulations with replications. According to my testing, sim objects are different from each other (e.g. `sim1.RDS` vs. `sim2.RDS` AND `sim1[[1]]@simlist[[1]]` vs. `sim1[[2]]@simlist[[1]]` )
Here is the code:
```
library(foreach)
library(doMC)
registerDoMC(64) # available cores
export <-"/myfolder/" #set your folder

#Default Data of library
library(BacArena)
data(Ec_core)
x<-Ec_core

# Make dataframe and set replicates
df <- data.frame('f' = 0,'t' = 0)
replicates <- 3 

#Simulation
output <- foreach(f = 1:64,.combine = 'rbind.data.frame')  %dopar% {
  simlist <- list() #Start
  for (t in 1:replicates)
  {
    arena <- NA
    setting <- list()
    number <- f
    bac_wild <- BacArena::Bac(model=x) 
    arena <- BacArena::Arena(n=10, m=10)
    arena <- BacArena::addOrg(arena, bac_wild, amount=number)
    arena <- BacArena::addSubs(object = arena, smax = 1)
    setting <- BacArena::simEnv(arena, time=5, continue = T)
    simlist[[t]] <- setting
  }    #End
  saveRDS(simlist, file = paste(export,'sim', f, ".RDS",sep = ''))
  df[1,1] <- f #test that f changes per loop cycle
  df[1,2] <- t #test that t finished all loop cycles
  rbind.data.frame(df)
}
saveRDS(output, paste(export,'output.RDS',sep = ''))  
```
I look forward to your comments!

**Comment by maringos** [comment]
By the way I should inform you that in big scale simulations the code freezes without any error or message. This phenomenon is untraceable and inconsistent, so nor I can blame anything neither anyone! :-1:

**Comment by maringos** [comment]
Keeping informing....
I run 78 simulations with 3 replicates each by using the method @jotech proposed. Unfortunately 3 of 78 are frozen: No output, no error, only keep running for more than one day! I am starting thinking that the models are sometimes "corrupt" sometimes "healthy".

**Comment by maringos** [comment]
By using CPLEX I have never encountered this issue again. :)
